-d /Users/hanqnero/Documents/uni/Semester 5/Programming_fpga/lab4/project/lab4-2/impl/gwsynthesis/lab4-2.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst /Users/hanqnero/Documents/uni/Semester 5/Programming_fpga/lab4/project/lab4-2/src/lab4-2.cst
-cfg /Users/hanqnero/Documents/uni/Semester 5/Programming_fpga/lab4/project/lab4-2/impl/pnr/device.cfg
-sdc /Users/hanqnero/Documents/uni/Semester 5/Programming_fpga/lab4/project/lab4-2/src/lab4-2.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
